# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4bfa30aff0d3412a2a4e7058c075addc71273b8611cd9a8f8dd29f382592666123b742a8407086ed82e14a55d83bcb945d00f037ea67dcb3f3f02bf3782693e

test:
  secret_key_base: 7806ccadee01fa761c6d7836c683457d8164095a968d189d5e567e0c239987077ace705d7430c8c696b5ce2b38f212982865e70aed131ef1e08af911b3207283

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
